spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: freteflow2

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${FRETEFLOW_RUNTIME_DB_USER}
    password: ${FRETEFLOW_RUNTIME_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    user: ${FRETEFLOW_MIGRATOR_DB_USER}
    password: ${FRETEFLOW_MIGRATOR_DB_PASSWORD}
    locations: classpath:db/migration

server:
  port: 8080
api:
  security:
    token:
      secret: ${JWT_SECRET}